- name: Reset Envirnment
  hosts: localhost
  tasks:
    - name: Include vars [TASK]
      include_vars:
        file: vars/cluster_variables
      tags: vars

    - name: Stop bootstrap and loadbalancer VMs
      virt:
        state: destroyed
        name: "{{ item }}"
      loop:
         - "{{ cluster_name }}-bootstrap"
         - "{{ cluster_name }}-loadbalancer"
      ignore_errors: yes
    
    - name: Stop all of the master VMs
      virt:
        state: destroyed
        name: "{{ cluster_name }}-master{{ item }}"
      with_sequence: "start=1 end={{ master_count }}"
      ignore_errors: yes
    
    - name: Stop all of the worker VMs
      virt:
        state: destroyed
        name: "{{ cluster_name }}-worker{{ item }}"
      with_sequence: "start=1 end={{ worker_count }}"
      ignore_errors: yes
    
    - name: Delete bootstrap and loadbalancer VMs
      command: 'virsh undefine --domain "{{ item }}"'
      loop:
         - "{{ cluster_name }}-bootstrap"
         - "{{ cluster_name }}-loadbalancer"
      ignore_errors: yes
    
    - name: Delete all of the master VMs
      command: "virsh undefine --domain {{ cluster_name }}-master{{ item }}"
      with_sequence: "start=1 end={{ master_count }}"
      ignore_errors: yes
    
    - name: Delete all of the worker VMs
      command: "virsh undefine --domain {{ cluster_name }}-worker{{ item }}"
      with_sequence: "start=1 end={{ worker_count }}"
      ignore_errors: yes
    
    - name: Delete bootstrap and loadbalancer images from {{ vms_disks_location }}
      file: 
        name: "{{ vms_disks_location }}{{ item }}.qcow2"
        state: absent
      loop:
         - "{{ cluster_name }}-bootstrap"
         - "{{ cluster_name }}-loadbalancer"
      ignore_errors: yes
    
    - name: Delete Master VMs images from {{ vms_disks_location }}
      file: 
        name: "{{ vms_disks_location }}{{ cluster_name }}-master{{ item }}.qcow2"
        state: absent
      with_sequence: "start=1 end={{ master_count }}"
      ignore_errors: yes

    - name: Delete Worker VMs images from {{ vms_disks_location }}
      file: 
        name: "{{ vms_disks_location }}{{ cluster_name }}-worker{{ item }}.qcow2"
        state: absent
      with_sequence: "start=1 end={{ worker_count }}"
      ignore_errors: yes
    
    - name: Delete configured cluster network
      virt_net:
        state: absent
        name: "{{ cluster_name }}"
      ignore_errors: yes
        
    - name: Remove dnsmasq configurations
      file: 
        path: "/etc/dnsmasq.d/{{ cluster_name }}.conf"
        state: absent
      ignore_errors: yes
    
    - name: Remove cluster virtual interface from dnsmasq
      lineinfile:
        state: absent
        line: "except-interface={{ cluster_name }}"
        path: "/etc/dnsmasq.d/except-interfaces.conf"
      ignore_errors: yes
    
    - name: Cleaning /etc/hosts file from masters records
      lineinfile:
        path: /etc/hosts
        regexp: "master-.*.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /etc/hosts file from etcd records
      lineinfile:
        path: /etc/hosts
        regexp: "etcd-.*.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /etc/hosts file from workers records
      lineinfile:
        path: /etc/hosts
        regexp: "worker-.*.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /etc/hosts file from loadbalancer record
      lineinfile:
        path: /etc/hosts
        regexp: "lb.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /etc/hosts file from api record
      lineinfile:
        path: /etc/hosts
        regexp: "api.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /etc/hosts file from api-int record
      lineinfile:
        path: /etc/hosts
        regexp: "api-int.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /etc/hosts file from bootstrap record
      lineinfile:
        path: /etc/hosts
        regexp: "bootstrap.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /root/.ssh/known_hosts file from masters records
      lineinfile:
        path: /root/.ssh/known_hosts
        regexp: "master-.*.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /root/.ssh/known_hosts file from workers records
      lineinfile:
        path: /root/.ssh/known_hosts
        regexp: "worker-.*.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /root/.ssh/known_hosts file from bootstrap record
      lineinfile:
        path: /root/.ssh/known_hosts
        regexp: "^bootstrap.{{ cluster_name }}.{{ domain_name }}.com"
        state: absent
      ignore_errors: yes
    
    - name: Cleaning /root/.ssh/known_hosts file from loadbalancer record
      lineinfile:
        path: /root/.ssh/known_hosts
        regexp: "^lb.{{ cluster_name }}.{{ domain_name }}"
        state: absent
      ignore_errors: yes

    - name: Delete downloads directory
      file:
        path: /var/www/html/downloads/
        state: absent
      when: delete_downloads|bool == true
      ignore_errors: yes
