- name: Downloading and Installing the required OCP4 cluster
  hosts: localhost
  vars:
    version: "{{ minorversion }}"
    microversion: "{{ microversion }}"
    ansible_ssh_private_key_file: ./ocp-ssh-key
  tasks:
    - name: Include vars [TASK]
      include_vars:
        file: vars/cluster_variables
      tags: vars

    - name: checks [TASK]
      import_tasks: tasks/checks.yaml
      tags: checks

    - name: versions [TASK]
      import_tasks: tasks/ocp_versions.yaml
      tags: versions

    - name: Install/enable required packages/services [TASK]
      import_tasks: tasks/prerequistes.yaml
      tags: prerequistes

    - name: Download required files [TASK]
      import_tasks: tasks/download.yaml
      tags: download

    - name: Create Ignition Files [TASK]
      import_tasks: tasks/ignition.yaml
      tags: ignitions

    - name: Configure KVM networks [TASK]
      import_tasks: tasks/network.yaml
      tags: networks

    - name: Configuring dnsmasq [TASK]
      import_tasks: tasks/dns.yaml
      tags: dns

    - name: Configure loadbalancer VM [TASK]
      import_tasks: tasks/loadbalancer.yaml
      tags: loadbalancer

    - name: Copy HAProxy configuration template to loadbalancer VM [TASK]
      import_tasks: tasks/haproxy.yaml
      tags: haproxy
      delegate_to: "192.168.{{ network_subnet_octet }}.9"

    - name: Configure bootstrap VM [TASK]
      import_tasks: tasks/bootstrap.yaml
      tags: bootstrap

    - name: Configure Matsers VMs [TASK]
      import_tasks: tasks/masters.yaml
      tags: masters

    - name: Configure workers VMs [TASK]
      import_tasks: tasks/workers.yaml
      tags: workers

    - name: Prepare OCP4 Deployment Files [TASK]
      import_tasks: tasks/predeployment.yaml
      tags: predeployment
   
    - name: Starting OCP4.x Installation [TASK]
      import_tasks: tasks/ocp_install.yaml
      tags: deployment
