- name: Restart libvertd and dnsmasq services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
     - libvirtd
     - dnsmasq

- name: Starting bootstrap VM
  virt:
    state: running
    name: "{{ item }}"
  loop:
     - "{{ cluster_name }}-bootstrap"

- name: Starting ALL of the master VMs
  virt:
    state: running
    name: "{{ cluster_name }}-master{{ item }}"
  with_sequence: "start=1 end={{ master_count }}"

- name: Starting ALL of the worker VMs
  virt:
    state: running
    name: "{{ cluster_name }}-worker{{ item }}"
  with_sequence: "start=1 end={{ worker_count }}"
