- name: Create Worker VMs
  command: 'virt-install --name {{ cluster_name }}-worker{{ item }} --disk path={{ vms_disks_location }}{{ cluster_name }}-worker{{ item }}.qcow2,size={{ vm_disk }} --ram {{ vm_mem }} --cpu host --vcpus {{ vm_cpu }} --os-type linux --os-variant rhel7.0 --network network={{ cluster_name }},mac="{{ macbase }}{{ mac }}"  --noautoconsole --location /var/www/html/downloads/{{ minorversion }}/rhcos/ --extra-args "nomodeset rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.inst.image_url=http://{{ bastion_ip }}/downloads/{{ minorversion }}/rhcos/{{ bios.stdout }} coreos.inst.ignition_url=http://{{ bastion_ip }}/downloads/{{ minorversion }}.{{ microversion }}/install_dir/{{ vm_ignition }}"'
  vars:
  - vm_cpu: "{{ worker_cpu }}"
    vm_mem: "{{ worker_mem }}"
    vm_disk: "{{ worker_disk }}"
    vm_ignition: "worker.ign"
    mac: "2{{ item }}"
  with_sequence: "start=1 end={{ worker_count }}"
  ignore_errors: yes

- name: Start worker VMs
  virt:
    state: running
    name: "{{ cluster_name }}-worker{{ item }}"
  with_sequence: "start=1 end={{ worker_count }}"
  ignore_errors: yes
