apiVersion: v1
baseDomain: {{ domain_name }}
compute:
- hyperthreading: Disabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Disabled
  name: master
  replicas: {{ master_count }}
metadata:
  name: {{ cluster_name }}
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{{ pullsecret }}'
sshKey: '{{ ssh_public_key }}'
